# Generated by Django 2.0.4 on 2018-04-04 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('patient_id', models.IntegerField(primary_key=True, serialize=False)),
                ('patient_name', models.CharField(max_length=100)),
                ('patient_age', models.IntegerField()),
                ('date', models.DateField()),
                ('patient_address', models.CharField(max_length=100)),
                ('doctor', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_bill', models.IntegerField()),
                ('others', models.IntegerField()),
                ('patient_id', models.ForeignKey(on_delete='true', to='app.Appointment')),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('designation', models.CharField(max_length=100)),
                ('specialization', models.CharField(max_length=100)),
                ('d_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('e_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('e_password', models.CharField(max_length=8)),
                ('e_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('Mobile_no', models.CharField(max_length=10)),
                ('e_address', models.CharField(max_length=100)),
                ('e_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('expirydate', models.DateField()),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('medicine_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.IntegerField(primary_key=True, serialize=False)),
                ('patient_name', models.CharField(max_length=100)),
                ('patient_age', models.IntegerField()),
                ('patient_disease', models.CharField(max_length=100)),
                ('patient_Mobileno', models.CharField(max_length=10)),
                ('patient_address', models.CharField(max_length=100)),
                ('patient_email', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NoOfWorkinghours', models.IntegerField()),
                ('e_id', models.ForeignKey(on_delete='true', to='app.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='WorkingHours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NoOfWorkinghours', models.IntegerField()),
                ('e_id', models.ForeignKey(on_delete='true', to='app.Employee')),
            ],
        ),
    ]
